version: '3.8'
services:
  postgres:
    image: postgres:alpine
    container_name: postgres-alpine
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network

  api:
    build:
      context: ./Homebroker/Homebroker
    container_name: homebroker-api
    ports:
      - "8080:8080" 
    depends_on:
      - postgres 
    environment:
      - ConnectionStrings__Postgres=Host=postgres;Port=5432;Database=mydatabase;Username=admin;Password=secret
      - ASPNETCORE_ENVIRONMENT=Development

volumes:
  postgres_data:

networks:
  postgres_network:
    driver: bridge